# Generated by Django 5.1.1 on 2025-01-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_aithread'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_prompt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_prompt_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
